name: Publish documentation

on:
  push:
    branches:
      - develop
      - 'actions/docs'
  pull_request:
    branches:
      - develop

jobs:
  docs:
    runs-on: ubuntu-18.04

    # name: Node ${{ matrix.node-version }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install
      run: |
        cd docs/website
        yarn install --frozen-lockfile

    - name: Build
      if: github.event_name == 'pull_request'
      run: |
        cd docs/website
        yarn run build
      env:
        CI: true

    - name: Publish
      if: github.event_name == 'push'
      run: |
        cd docs/website
        git config --global user.email "$DOC_USERNAME@users.noreply.github.com"
        git config --global user.name "$DOC_USERNAME"
        echo "machine github.com login $DOC_USERNAME password $DOC_TOKEN" > ~/.netrc
        GIT_USER=$DOC_USERNAME CURRENT_BRANCH=develop yarn run publish-gh-pages
      env:
        CI: true
        DOC_USERNAME: ${{ secrets.DOC_USERNAME }}
        DOC_TOKEN: ${{ secrets.DOC_TOKEN }}
